### ISSUE TITLE
Contact info for Hiring

### ISSUE THREAD

**Issue by webmiraclepro** [rmiyazaki6499/mern-app#28]
hi rmiyazaki
I am interested in your position
https://ghostbyte.io
https://oreoswap.finance
https://github.com/webmiraclepro
I have gone through your project requirements.
I am a blockchain engineer and fullstack developer with over 8 years of experience
my telegramId: @WebMiracle
discord:  WebMiracle#2749
please contact me.
Iooking forward to hearing from you

**Comment by HeraclesSiiz** [comment]
Hello,rmiyhazaki
I am interested in your job.
contact info:
my telegramId: @heraclesdev
skype:live:.cid.87d54f51c2062a68
Looing forward working with you

**Comment by sumitshinde-84** [comment]
hello, My name is Sumit Shinde, and I am a full-stack developer. I am currently a fresher and do not have any professional experience yet. However, I have contributed to many open-source projects and gained valuable experience through these contributions.

**Comment by rmiyazaki6499** [comment]
Hi everyone, sorry but I'm not hiring for anything because I too am also looking for work
This issue seems unrelated to the repo so will close

Wish you good luck on finding something in these tough times
